/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame.java
 *
 * Created on Jul 12, 2011, 3:32:00 PM
 */
package decidingFactorReturns.GUI;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JPanel;

/**
 *
 * @author marcos
 */
public class MainFrame extends javax.swing.JFrame {

    private Component activePanel;

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        this.getContentPane().setLayout(new BorderLayout());
        changePanel(new InitialMenuPanel());
    }

    private void changePanel(JPanel panel) {
        if (activePanel != null) {
            getContentPane().remove(activePanel);
        }
        activePanel = panel;
        getContentPane().add(activePanel, BorderLayout.CENTER);
        Dimension screenSize = getToolkit().getScreenSize();
        this.setLocation((screenSize.width - activePanel.getWidth()) / 2, (screenSize.height - activePanel.getHeight()) / 2);
        pack();
        repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
